[package]
name = "json"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
walkdir = "2.5"
serde_json = "1.0"
serde_jsonc = "1.0.108"
serde_json5 = "1.0"
serde_hjson = "1.1"
regex = "1.11"
